### ISSUE TITLE
Add Stack Account Self-Service Features

### ISSUE THREAD

**Issue by bootsie123** [ritsec/ops-bot-iii#135]
**Is your feature request related to a problem? Please describe.**

Right now when a member needs to either create an OpenStack account or get their password reset, they need to open up a ticket. While this usually isn't an issue, there are times during the beginning of each semester where we have an influx of these requests and it can overload the ops team. This feature aims to automate this process by letting OBIII do the work.

**Describe the solution you'd like**

This feature would enable OpenStack self-service for members. This would be through `/openstack` commands such as `/openstack create` and `/openstack reset`.

For `/openstack create`, any user who is a verified member and doesn't already have a stack account would be able to have one automatically provisioned. This would include the following:
   - Create an OpenStack account following the `xyz1234@rit.edu --> xya1234 (OpenStack Username)` format based on the user's email address with a randomly generated password set
   - Create an OpenStack project with the same name as the OpenStack username
   - Set the created project quota to the default [found here](https://gitlab.ritsec.cloud/operations-program/openstack-user-create)
   - Add the user to the project using the `member` role
   - Send the user their account password through a Discord DM

For `/openstack reset`, any user who is a verified member and has a stack account would be able to get their password reset to a randomly generated password. This password would then be sent to them through a Discord DM.

**Additional context**
Password reset as part of the self-service would be great but it's not essential. For right now, account creation is the big one.

**Comment by c0untingNumbers** [comment]
Some users don't allow DMs so I will have to have a function that checks if their DMs are open first before doing any of this step.
