### ISSUE TITLE
Additional Sign-in Option

### ISSUE THREAD

**Issue by leahkvares** [ritsec/ops-bot-iii#138]
**Is your feature request related to a problem? Please describe.**
Mentorship attendance is difficult to track. Integration with OBIII would make it a much faster and smoother process for both the Head of Education and the mentors because it is important to be able to correlate Discord usernames with sign-ins.

**Describe the solution you'd like**
Add a "Mentorship" option for the /signin command. This will be used for mentorship group meetings to keep track of attendance for general metrics as well as to be able to award prizes based on mentees' attendance.

**Describe alternatives you've considered**
Mentors would have to manually write down who is present each time or create a form for mentees to fill out at each meeting.

**Comment by c0untingNumbers** [comment]
Vote command will have to ignore this type since mentorship attendance is not defined for the member in the RITSEC constitution.

Should be easy to add/change the query that does not query for the mentorship signins.
