### ISSUE TITLE
Automatically signin user who creates signin

### ISSUE THREAD

**Issue by voxelvortex** [ritsec/ops-bot-iii#70]
**Is your feature request related to a problem? Please describe.**
IG leads sometimes have low signins for the IG they lead because they forget to click the signin button after creating a signin. 

**Describe the solution you'd like**
Signin creators should automatically be signed in to the IG they've created a signin for.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by 1nv8rzim** [comment]
@c0untingNumbers 

This should be as simple as adding these lines:

https://github.com/ritsec/ops-bot-iii/blob/main/commands/slash/signin.go#L153-L197

to here:

https://github.com/ritsec/ops-bot-iii/blob/main/commands/slash/signin.go#L101

Some things to be careful with:
- change user to be the person executing command, should be something like `i.Member.User.ID`
- refactor interaction respond to command executer (interactions can only be responded to once, respond on error, or once at the end with the new information that they have also been signed in)
