### ISSUE TITLE
Role join button for birdos

### ISSUE THREAD

**Issue by raf1843** [ritsec/ops-bot-iii#89]
**Is your feature request related to a problem? Please describe.**
I cannot add buttons to role-join (secretary skill issue?) and would like to allow people to join birdos channel and share bird pictures

**Describe the solution you'd like**
Add a role-join button for birdos, in the same section as cattos and doggos

**Describe alternatives you've considered**
Please

**Additional context**
![image](https://github.com/ritsec/ops-bot-iii/assets/90727927/550394e0-98fd-48be-b1bb-a3e3da106bf1)

Actually I would just like E-board to be able to edit obiii roles tbh

**Comment by c0untingNumbers** [comment]
Unrelated to OBIII. However, I will document on how to add buttons for role-join text channel.
