### ISSUE TITLE
Chase's "Guys what do I do" post in #shitposting not in 1st place on scoreboard when it should be

### ISSUE THREAD

**Issue by c0untingNumbers** [ritsec/ops-bot-iii#90]
**Describe the bug**
The message by ChaseK that has the most :angryreact:s (53) was initially on the scoreboard in 1st place but does not show up anymore. Instead, Kenny's message that has 38 :angryreact:s shows up as 1st instead.

**To Reproduce**
1. Type /scoreboard
2. See that ChaseK's post is not on there in 1st place or at all

**Expected behavior**
ChaseK's message listed as 1st instead of Kenny's message.

**Logs and Evidence**
![image](https://github.com/ritsec/ops-bot-iii/assets/39505290/f57b792a-39b5-49a7-8bc6-621aa586791e)
![image](https://github.com/ritsec/ops-bot-iii/assets/39505290/f9ee9296-4417-4dd1-89b6-ba82eb016e1d)

**Comment by c0untingNumbers** [comment]
Seems to be random because it is back now? Who knows? Will check back later.

**Comment by 1nv8rzim** [comment]
I’ve seen this before and I have no idea why it happens. If you remove and add an angry react to post will fix itself.
