### ISSUE TITLE
Change DFIR IG to IR IG

### ISSUE THREAD

**Issue by c0untingNumbers** [ritsec/ops-bot-iii#91]
**Describe the solution you'd like**
See IR instead of DFIR

**Comment by 1nv8rzim** [comment]
A couple things you have do for this:

Change this from "DFIR" to "IR":

https://github.com/ritsec/ops-bot-iii/blob/ab94a06d5988a9edbf06feef69865295d184a458/ent/schema/signin.go#L33

Generate Code from ent schema:

```bash
go generate ./...
```

Change these from "DFIR" to IR:

https://github.com/ritsec/ops-bot-iii/blob/ab94a06d5988a9edbf06feef69865295d184a458/commands/slash/signin.go#L43-L44

https://github.com/ritsec/ops-bot-iii/blob/ab94a06d5988a9edbf06feef69865295d184a458/commands/slash/signin.go#L119-L120
